device_map: "auto"
mixed_precision: "fp16"
num_processes: 1
num_machines: 1
machine_rank: 0
main_process_ip: "127.0.0.1"
main_process_port: 29500
use_cpu: false
gradient_accumulation_steps: 1
max_grad_norm: 1.0
train_batch_size: 8
eval_batch_size: 8
gradient_checkpointing: true
logging_dir: "./logs"
logging_steps: 100
save_steps: 500
evaluation_strategy: "steps"
save_total_limit: 2
fp16_opt_level: "O1"