loggers:
  console:
    level: INFO
    formatter: detailed
  file:
    level: DEBUG
    formatter: detailed
    filename: logs/training.log
    maxBytes: 10485760
    backupCount: 5

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

root:
  level: INFO
  handlers: [console, file]